services:
  docs:
    image: oh_mazette_local_docs
    container_name: oh_mazette_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./oh_mazette:/app/oh_mazette:z
    ports:
      - '9000:9000'
    command: /start-docs
